import {
  Server,
  Database,
  Globe,
  Shield,
  Users,
  FileText,
  GitBranch,
  MessageSquare,
  BarChart3,
  Zap,
  Building,
  Workflow,
  Brain,
  Smartphone,
  Calendar,
  Target,
} from "lucide-react"

export const atlassianComponents = [
  {
    id: "jira-software",
    name: "Jira Software",
    description: "Project management and issue tracking",
    category: "Core Products",
    icon: Server,
    color: "bg-blue-500",
  },
  {
    id: "jira-service-management",
    name: "Jira Service Management",
    description: "IT service management and support",
    category: "Core Products",
    icon: Shield,
    color: "bg-green-500",
  },
  {
    id: "jira-work-management",
    name: "Jira Work Management",
    description: "Business team project management",
    category: "Core Products",
    icon: Server,
    color: "bg-blue-600",
  },
  {
    id: "confluence",
    name: "Confluence",
    description: "Team collaboration and documentation",
    category: "Core Products",
    icon: FileText,
    color: "bg-purple-500",
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    description: "Git repository management",
    category: "Core Products",
    icon: GitBranch,
    color: "bg-indigo-500",
  },
  {
    id: "compass",
    name: "Compass",
    description: "Developer experience platform",
    category: "Platform",
    icon: BarChart3,
    color: "bg-orange-500",
  },
  {
    id: "atlas",
    name: "Atlas",
    description: "Teamwork directory and insights",
    category: "Platform",
    icon: Users,
    color: "bg-pink-500",
  },
  {
    id: "jira-align",
    name: "Jira Align",
    description: "Enterprise agile planning",
    category: "Enterprise",
    icon: BarChart3,
    color: "bg-emerald-500",
  },
  {
    id: "jira-product-discovery",
    name: "Jira Product Discovery",
    description: "Product roadmap and discovery",
    category: "Product Management",
    icon: Workflow,
    color: "bg-violet-500",
  },
  {
    id: "trello",
    name: "Trello",
    description: "Visual project management boards",
    category: "Core Products",
    icon: Server,
    color: "bg-blue-400",
  },
  {
    id: "bamboo",
    name: "Bamboo",
    description: "Continuous integration and deployment",
    category: "DevOps",
    icon: Zap,
    color: "bg-yellow-500",
  },
  {
    id: "crowd",
    name: "Crowd",
    description: "Identity management and single sign-on",
    category: "Security",
    icon: Shield,
    color: "bg-teal-500",
  },
  {
    id: "fisheye-crucible",
    name: "Fisheye & Crucible",
    description: "Code review and repository browsing",
    category: "DevOps",
    icon: GitBranch,
    color: "bg-cyan-500",
  },
  {
    id: "atlassian-access",
    name: "Atlassian Access",
    description: "Enterprise security and user management",
    category: "Security",
    icon: Shield,
    color: "bg-red-600",
  },
  {
    id: "atlassian-analytics",
    name: "Atlassian Analytics",
    description: "Cross-product analytics and insights",
    category: "Analytics",
    icon: BarChart3,
    color: "bg-purple-600",
  },
  {
    id: "statuspage",
    name: "Statuspage",
    description: "Status communication platform",
    category: "Operations",
    icon: Globe,
    color: "bg-cyan-500",
  },
  {
    id: "opsgenie",
    name: "Opsgenie",
    description: "Incident management and alerting",
    category: "Operations",
    icon: MessageSquare,
    color: "bg-red-500",
  },
  {
    id: "atlassian-marketplace",
    name: "Atlassian Marketplace",
    description: "App marketplace and ecosystem",
    category: "Platform",
    icon: Building,
    color: "bg-indigo-600",
  },
  {
    id: "atlassian-intelligence",
    name: "Atlassian Intelligence",
    description: "AI-powered features across Atlassian products",
    category: "AI/ML",
    icon: Brain,
    color: "bg-violet-600",
  },
  {
    id: "atlassian-mobile",
    name: "Atlassian Mobile Apps",
    description: "Mobile applications for iOS and Android",
    category: "Mobile",
    icon: Smartphone,
    color: "bg-gray-600",
  },
  {
    id: "team-calendars",
    name: "Team Calendars",
    description: "Team scheduling and calendar management",
    category: "Productivity",
    icon: Calendar,
    color: "bg-blue-500",
  },
  {
    id: "portfolio-for-jira",
    name: "Portfolio for Jira",
    description: "Advanced project portfolio management",
    category: "Enterprise",
    icon: Target,
    color: "bg-green-600",
  },
  {
    id: "database-primary",
    name: "Primary Database",
    description: "Main application database",
    category: "Infrastructure",
    icon: Database,
    color: "bg-gray-500",
  },
  {
    id: "database-analytics",
    name: "Analytics Database",
    description: "Data warehouse and analytics",
    category: "Infrastructure",
    icon: Database,
    color: "bg-yellow-500",
  },
]
